### ISSUE TITLE
Tree Conversion Error

### ISSUE THREAD

**Issue by simonschnake** [JuliaHEP/UpROOT.jl#1]
Hey, I tried to open a TTree with uproot.jl and got the following error
Error showing value of type TTree:
ERROR: KeyError: key "__name__" not found
Stacktrace:
 [1] getproperty(::PyObject, ::String) at .../packages/PyCall/ttONZ/src/PyCall.jl:308
 [2] getproperty(::PyObject, ::Symbol) at .../packages/PyCall/ttONZ/src/PyCall.jl:313
 [3] awkwardobjectarray2jl(::PyObject) at .../packages/UpROOT/nF6Gy/src/pyjlconv.jl:25

It seems that the PyCall Code has changed.

**Comment by oschulz** [comment]
Could you try this again?There have been a few changes/improvements in the mean time.

**Comment by simonschnake** [comment]
Hello oschulz,
I have left particle physics and not using ROOT anymore. I therefore have no fitting ROOT environment at the moment and no time to install it again. Thanks for you time and development.
Cheers 
Simon

**Comment by oschulz** [comment]
Thanks!

**Comment by oschulz** [comment]
Closing this, until it crops up again.
