### ISSUE TITLE
tree[:,:] vs tree[:,propertynames(tree)]

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaHEP/UpROOT.jl#12]
![image](https://user-images.githubusercontent.com/22725744/89883359-58530780-dbc8-11ea-99ab-0809853e807c.png)

also asked on discourse
https://discourse.julialang.org/t/tables-jl-uproot-jl-and-the-speed/44737/4

**Comment by oschulz** [comment]
Could you make that data file available?

**Comment by oschulz** [comment]
In general, this happens when iterating over a TTree serially, entry by entry - that's slow with UpROOT, due to the way Python uproot works. However, you're doing a multi-entry `getindex` in both cases. I'd really like to have a similar file to test with.

**Comment by mmikhasenko** [comment]
Thanks for looking at it.
```c++
#include "TString.h"
#include "TFile.h"
#include "TTree.h"

#include <string>
#include "stdlib.h"

int create_file() {

  TFile *f = new TFile("test_tree.root", "recreate");
  TTree *t = new TTree("mytree", "mytree");

  auto app = "EXYZ";
  const uint Np = 4;
  std::string names[Np] = {"pBeam", "pPim", "pEta", "pRecoil"};

  //
  double v[Np][4];
  for (uint n=0; n<Np; n++)
    for (uint i=0; i<4; i++)
      t->Branch(TString::Format("%s_%c",names[n].c_str(), app[i]), &v[n][i]);

  const int Nev = 300000;

  for (uint i=0; i <= Nev; i++) {
    for (uint n=0; n<Np; n++)
      for (uint i=0; i<4; i++)
	v[n][i] = (rand() % 100) / 100.0;
    //
    t->Fill();
  }

  t->Write();
  f->Close();

  return 0;
}
```

**Comment by mmikhasenko** [comment]
> In general, this happens when iterating over a TTree serially, entry by entry - that's slow with UpROOT, due to the way Python uproot works. However, you're doing a multi-entry `getindex` in both cases. I'd really like to have a similar file to test with.

**Comment by oschulz** [comment]
Why did you close the issue - is this resolved?

**Comment by mmikhasenko** [comment]
Ha, by mistake, I did not notice. Perhaps, the cat walked on the keyboard

**Comment by mmikhasenko** [comment]
I do not see the way to reopen

**Comment by oschulz** [comment]
Hehe, Ok, I'll take a look then.

**Comment by mmikhasenko** [comment]
I will be showing `Julia` to the CERN students on Friday. Nervous as introducing a new girlfriend to parents

**Comment by oschulz** [comment]
Oh, nice! Anything you need for that, last-minute, that I can help with?

**Comment by mmikhasenko** [comment]
thanks! the uproot part works nicely. Enjoy the vacation!

**Comment by mmikhasenko** [comment]
wrong place for posting. I was making a similar example for investigation in UnROOT.
I think this issue can be closed.

**Comment by oschulz** [comment]
Thanks!
