### ISSUE TITLE
UpROOT crashes Atom

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaHEP/UpROOT.jl#7]
When `julia` is killed while the `TTree` reading is being processed Atom crashes.

![image](https://user-images.githubusercontent.com/22725744/75342656-1ee74380-5897-11ea-9e2b-c7be6d283692.png)

```
Julia 1.3.0
Windows 10
```

Can someone reproduce?

**Comment by oschulz** [comment]
Haven't seen this, but I rarely use Atom, and I'm on Linux. This one could get tricky to track down, with Julia, Atom and Python in the mix ...

**Comment by oschulz** [comment]
I wonder if the is specific to UpROOT.jl, or if it would happy when killing Julia while any kind of PyCall operation is running?

**Comment by mmikhasenko** [comment]
Yes, it is most likely. I recently spotted the same behavior when UpROOT was not imported.

**Comment by oschulz** [comment]
Ah, right - shall we close this issue then? Probably needs to be raised with the PyCall developers.

**Comment by mmikhasenko** [comment]
yes, agree
